[package]
name = "cloudflare-ddns-updater"
version = "0.2.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "3.0", features = ["derive"] }
cloudflare = "0.9"
env_logger = "0.9"
log = "0.4"
matrix-sdk = { version = "0.5.0", default-features = false, features = ["native-tls"] }
public-ip = { version = "0.2", default-features = false, features = ["tokio-http-resolver", "whatismyipaddress-com", "ipify-org"] }
serde = "1.0"
tokio = { version = "1.16" , features = ["full"] }
toml = "0.5"
